### ISSUE TITLE
Memship install error

### ISSUE THREAD

**Issue by bill-curran** [leegarner-glfusion/membership#6]
23 Jul 2020 21:04:08 EDT - 198.251.54.0: AutoInstall: **** Start Installation **** 
23 Jul 2020 21:04:08 EDT - 198.251.54.0: AutoInstall: Creating table gl_membership_members... 
**23 Jul 2020 21:04:08 EDT - 198.251.54.0: 42000: Key column 'guid' doesn't exist in table** 
23 Jul 2020 21:04:08 EDT - 198.251.54.0: AutoInstall: Failed to create table gl_membership_members! 
23 Jul 2020 21:04:08 EDT - 198.251.54.0: Auto-uninstalling plugin membership:

**Comment by leegarner** [comment]
Sync'd installation SQL with actual schema in develop, e307bbac5d2d798fca8861f985244bcd46d0e409
